[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
data = { path = "../data" }

leptos = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
gloo-net = { workspace = true }
serde_urlencoded = { workspace = true }
urlencoding = { workspace = true }
js-sys = { workspace = true }
serde-wasm-bindgen = { workspace = true }
# Todo: This getrandom dependency needs to be defined this way (dependencies + target.wasm.dependencies) in different versions, else it does not compile to wasm32-unknown-unknown target.
getrandom = { version="0.2.16" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version="0.3.4", features = ["wasm_js"] }
