[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
data = { path = "../data" }

console_error_panic_hook = { workspace = true }
leptos = { workspace = true }
leptos-use = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
gloo-net = { workspace = true }
serde_urlencoded = { workspace = true }
urlencoding = { workspace = true }
js-sys = { workspace = true }
serde-wasm-bindgen = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
tracing-web = { workspace = true }

# use default backend for getrandom
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
getrandom = { workspace = true }

# getrandom needs another backend when compiled to wasm
[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true, features = ["wasm_js"] }
