[package]
name = "server"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"


[dependencies]
data = { path = "../data" }
ai_models = { path = "../ai_models" , features = ["yolo","age_gender", "arcface", "clip"] }

axum = { workspace = true }
chrono = { workspace = true }
tonic = { workspace = true }
tonic-web = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
axum-server = { workspace = true }
env_logger = { workspace = true }
expanduser = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
clap = { workspace = true }
surrealdb = { workspace = true }
surrealdb-types = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "ansi", "tracing-log"] }
walkdir = { workspace = true }
urlencoding = { workspace = true }
rand = { workspace = true }
burn = { workspace = true }
burn-wgpu = { workspace = true }
burn-ndarray = { workspace = true }
image = { workspace = true }
rayon = { workspace = true }
bytemuck = { workspace = true }
anyhow = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }

[profile.dev]
opt-level = 1               # Use slightly better optimizations, reduces debug build size
