[package]
name = "ai_models"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { workspace = true }
burn-store = { workspace = true }
image = { workspace = true }

[build-dependencies]
onnx_updater = { path = "../onnx_updater" }

anyhow = { workspace = true }
burn-import = { workspace = true }
hf-hub = { workspace = true }

[features]
default = []
arcface = []
yolo = []
age_gender = []
clip = []